"""add clinical domain

: the clinical domain — a member's health
profile. Three natural-key link tables (``member_diagnoses``,
``member_procedures``, ``member_medications``) with period semantics
(``starts_on``/``ends_on``, states derived from dates, deliberately no
uniqueness constraints — recurrence is multiple rows) and the one-to-one
``member_demographics`` (``height_in`` stored in inches). Terminology
linkage is by ICD-10 code / FDA product_id with no cross-domain FK.
Additive only — the downgrade drops the four tables.

Revision ID: 289bf468c1eb
Revises: 8c41d7b02a96
Create Date: 2026-07-17 14:11:42.859826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "289bf468c1eb"
down_revision: Union[str, None] = "8c41d7b02a96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_demographics",
        sa.Column("member_user_id", sa.String(), nullable=False),
        sa.Column("sex", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("ethnicity", sa.String(), nullable=True),
        sa.Column("marital_status", sa.String(), nullable=True),
        sa.Column("height_in", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_user_id"],
            ["user_profiles.id"],
            name=op.f("fk_member_demographics_member_user_id_user_profiles"),
        ),
        sa.PrimaryKeyConstraint("member_user_id", name=op.f("pk_member_demographics")),
    )
    op.create_table(
        "member_diagnoses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("member_user_id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_user_id"],
            ["user_profiles.id"],
            name=op.f("fk_member_diagnoses_member_user_id_user_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_member_diagnoses")),
    )
    op.create_table(
        "member_medications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("member_user_id", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_user_id"],
            ["user_profiles.id"],
            name=op.f("fk_member_medications_member_user_id_user_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_member_medications")),
    )
    op.create_table(
        "member_procedures",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("member_user_id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_user_id"],
            ["user_profiles.id"],
            name=op.f("fk_member_procedures_member_user_id_user_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_member_procedures")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("member_procedures")
    op.drop_table("member_medications")
    op.drop_table("member_diagnoses")
    op.drop_table("member_demographics")
    # ### end Alembic commands ###
