"""add device_readings domain

Revision ID: 45ecb77282f3
Revises: aa8d5f63f640
Create Date: 2026-07-13 17:30:08.240546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45ecb77282f3'
down_revision: Union[str, None] = 'aa8d5f63f640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_readings')),
    sa.UniqueConstraint('correlation_id', name=op.f('uq_raw_readings_correlation_id'))
    )
    op.create_table('readings_outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readings_outbox_events'))
    )
    op.create_table('user_external_id_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_external_id_types')),
    sa.UniqueConstraint('name', name=op.f('uq_user_external_id_types_name'))
    )
    # The type catalogue is reference data with DETERMINISTIC ids — names and ids must match
    # strata_core.domains.device_readings EXTERNAL_ID_TYPE_NAMES/EXTERNAL_ID_TYPE_IDS
    # (asserted by the round-trip test), so every database carries identical catalogue rows
    # and nothing needs an id lookup. A closed list: further types (NHS Number, Django User
    # ID) are seeded by a future migration when a feature needs them.
    types = sa.table('user_external_id_types', sa.column('id', sa.String()), sa.column('name', sa.String()))
    op.bulk_insert(types, [{'id': 'extid-' + n.lower().replace(' ', '-'), 'name': n} for n in ('SmartMeter Scale', 'SmartMeter Blood Pressure')])
    op.create_table('blood_pressure_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('provider_reading_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('systolic_mmhg', sa.Integer(), nullable=False),
    sa.Column('diastolic_mmhg', sa.Integer(), nullable=False),
    sa.Column('pulse_bpm', sa.Integer(), nullable=False),
    sa.Column('irregular', sa.Boolean(), nullable=False),
    sa.Column('suspect', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('raw_ref', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_ref'], ['raw_readings.id'], name=op.f('fk_blood_pressure_readings_raw_ref_raw_readings')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_blood_pressure_readings_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_pressure_readings')),
    sa.UniqueConstraint('correlation_id', name=op.f('uq_blood_pressure_readings_correlation_id')),
    sa.UniqueConstraint('provider_reading_id', name=op.f('uq_blood_pressure_readings_provider_reading_id'))
    )
    op.create_table('quarantined_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('raw_ref', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('reading_type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_ref'], ['raw_readings.id'], name=op.f('fk_quarantined_readings_raw_ref_raw_readings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarantined_readings'))
    )
    op.create_index('uq_quarantined_readings_open', 'quarantined_readings', ['correlation_id'], unique=True, postgresql_where=sa.text("state = 'open'"))
    op.create_table('reading_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('raw_ref', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('receive_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_ref'], ['raw_readings.id'], name=op.f('fk_reading_queue_raw_ref_raw_readings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_queue'))
    )
    op.create_index('ix_reading_queue_ready', 'reading_queue', ['state'], unique=False, postgresql_where=sa.text("state = 'ready'"))
    op.create_table('user_external_ids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['user_external_id_types.id'], name=op.f('fk_user_external_ids_type_id_user_external_id_types')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_user_external_ids_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_external_ids'))
    )
    op.create_index('uq_user_external_ids_active', 'user_external_ids', ['type_id', 'external_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_table('weight_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('provider_reading_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('tare_kg', sa.Numeric(), nullable=True),
    sa.Column('weight_lbs', sa.Numeric(), nullable=True),
    sa.Column('tare_lbs', sa.Numeric(), nullable=True),
    sa.Column('suspect', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('raw_ref', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight_kg IS NOT NULL OR weight_lbs IS NOT NULL', name=op.f('ck_weight_readings_has_measurement')),
    sa.ForeignKeyConstraint(['raw_ref'], ['raw_readings.id'], name=op.f('fk_weight_readings_raw_ref_raw_readings')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_weight_readings_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_readings')),
    sa.UniqueConstraint('correlation_id', name=op.f('uq_weight_readings_correlation_id')),
    sa.UniqueConstraint('provider_reading_id', name=op.f('uq_weight_readings_provider_reading_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_readings')
    op.drop_index('uq_user_external_ids_active', table_name='user_external_ids', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_table('user_external_ids')
    op.drop_index('ix_reading_queue_ready', table_name='reading_queue', postgresql_where=sa.text("state = 'ready'"))
    op.drop_table('reading_queue')
    op.drop_index('uq_quarantined_readings_open', table_name='quarantined_readings', postgresql_where=sa.text("state = 'open'"))
    op.drop_table('quarantined_readings')
    op.drop_table('blood_pressure_readings')
    op.drop_table('user_external_id_types')
    op.drop_table('readings_outbox_events')
    op.drop_table('raw_readings')
    # ### end Alembic commands ###
