"""baseline canonical schema

Revision ID: 5797a5167e94
Revises: 
Create Date: 2026-07-09 17:30:27.531246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5797a5167e94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm backs the substring (ILIKE) search GIN indexes on the reference tables;
    # create it first so those CREATE INDEX statements succeed.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('short_title', sa.Text(), nullable=False),
    sa.Column('long_title', sa.Text(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses')),
    sa.UniqueConstraint('code', name=op.f('uq_diagnoses_code'))
    )
    op.create_index('ix_diagnoses_long_title_trgm', 'diagnoses', ['long_title'], unique=False, postgresql_using='gin', postgresql_ops={'long_title': 'gin_trgm_ops'})
    op.create_table('procedures',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('short_title', sa.Text(), nullable=False),
    sa.Column('long_title', sa.Text(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedures')),
    sa.UniqueConstraint('code', name=op.f('uq_procedures_code'))
    )
    op.create_index('ix_procedures_long_title_trgm', 'procedures', ['long_title'], unique=False, postgresql_using='gin', postgresql_ops={'long_title': 'gin_trgm_ops'})
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('product_ndc', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=True),
    sa.Column('brand_name_base', sa.Text(), nullable=True),
    sa.Column('generic_name', sa.Text(), nullable=True),
    sa.Column('labeler_name', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.Text(), nullable=True),
    sa.Column('product_type', sa.Text(), nullable=True),
    sa.Column('marketing_category', sa.Text(), nullable=True),
    sa.Column('marketing_start_date', sa.Date(), nullable=True),
    sa.Column('marketing_end_date', sa.Date(), nullable=True),
    sa.Column('listing_expiration_date', sa.Date(), nullable=True),
    sa.Column('dea_schedule', sa.Text(), nullable=True),
    sa.Column('application_number', sa.Text(), nullable=True),
    sa.Column('spl_id', sa.Text(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('routes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('pharm_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('product_id', name=op.f('uq_products_product_id'))
    )
    op.create_index('ix_products_brand_trgm', 'products', ['brand_name'], unique=False, postgresql_using='gin', postgresql_ops={'brand_name': 'gin_trgm_ops'})
    op.create_index('ix_products_generic_trgm', 'products', ['generic_name'], unique=False, postgresql_using='gin', postgresql_ops={'generic_name': 'gin_trgm_ops'})
    op.create_index('ix_products_ndc', 'products', ['product_ndc'], unique=False)
    op.create_table('programmes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('suggestion_window_hours', sa.Integer(), nullable=False),
    sa.Column('reassignment_notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('no_show_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('reminder_lead_hours', sa.Integer(), nullable=False),
    sa.Column('slot_horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('reschedule_link_ttl_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programmes'))
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    # The role catalogue is reference data with DETERMINISTIC ids — names and ids must
    # match strata_core.domains.kernel.ROLE_NAMES/ROLE_IDS (asserted by the round-trip test),
    # so every database carries identical catalogue rows and nothing needs an id lookup.
    roles = sa.table('roles', sa.column('id', sa.String()), sa.column('name', sa.String()))
    op.bulk_insert(roles, [{'id': f'role-{n.lower()}', 'name': n} for n in ('Coach', 'Member', 'Admin')])
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cognito_sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    op.create_index(op.f('ix_user_profiles_cognito_sub'), 'user_profiles', ['cognito_sub'], unique=True)
    op.create_table('active_ingredients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('product_pk', sa.BigInteger(), nullable=False),
    sa.Column('ord', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_pk'], ['products.id'], name=op.f('fk_active_ingredients_product_pk_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_ingredients'))
    )
    op.create_index(op.f('ix_active_ingredients_product_pk'), 'active_ingredients', ['product_pk'], unique=False)
    op.create_index('ix_ai_name_trgm', 'active_ingredients', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('member_details',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_member_details_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_member_details'))
    )
    op.create_table('packagings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('product_pk', sa.BigInteger(), nullable=False),
    sa.Column('package_ndc', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('marketing_start_date', sa.Date(), nullable=True),
    sa.Column('marketing_end_date', sa.Date(), nullable=True),
    sa.Column('sample', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_pk'], ['products.id'], name=op.f('fk_packagings_product_pk_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packagings'))
    )
    op.create_index(op.f('ix_packagings_product_pk'), 'packagings', ['product_pk'], unique=False)
    op.create_index('ix_pkg_ndc', 'packagings', ['package_ndc'], unique=False)
    op.create_table('product_identifiers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('product_pk', sa.BigInteger(), nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_pk'], ['products.id'], name=op.f('fk_product_identifiers_product_pk_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_identifiers'))
    )
    op.create_index('ix_ident_lookup', 'product_identifiers', ['system', 'value'], unique=False)
    op.create_index(op.f('ix_product_identifiers_product_pk'), 'product_identifiers', ['product_pk'], unique=False)
    op.create_table('programme_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('programme_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_programme_assignments_programme_id_programmes')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_programme_assignments_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_programme_assignments_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programme_assignments')),
    sa.UniqueConstraint('programme_id', 'user_id', 'role_id', name=op.f('uq_programme_assignments_programme_id_user_id_role_id'))
    )
    op.create_table('user_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_user_roles_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id_role_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('programme_assignments')
    op.drop_index(op.f('ix_product_identifiers_product_pk'), table_name='product_identifiers')
    op.drop_index('ix_ident_lookup', table_name='product_identifiers')
    op.drop_table('product_identifiers')
    op.drop_index('ix_pkg_ndc', table_name='packagings')
    op.drop_index(op.f('ix_packagings_product_pk'), table_name='packagings')
    op.drop_table('packagings')
    op.drop_table('member_details')
    op.drop_index('ix_ai_name_trgm', table_name='active_ingredients', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_active_ingredients_product_pk'), table_name='active_ingredients')
    op.drop_table('active_ingredients')
    op.drop_index(op.f('ix_user_profiles_cognito_sub'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('roles')
    op.drop_table('programmes')
    op.drop_index('ix_products_ndc', table_name='products')
    op.drop_index('ix_products_generic_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'generic_name': 'gin_trgm_ops'})
    op.drop_index('ix_products_brand_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'brand_name': 'gin_trgm_ops'})
    op.drop_table('products')
    op.drop_index('ix_procedures_long_title_trgm', table_name='procedures', postgresql_using='gin', postgresql_ops={'long_title': 'gin_trgm_ops'})
    op.drop_table('procedures')
    op.drop_index('ix_diagnoses_long_title_trgm', table_name='diagnoses', postgresql_using='gin', postgresql_ops={'long_title': 'gin_trgm_ops'})
    op.drop_table('diagnoses')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
