"""add booking domain

Revision ID: aa8d5f63f640
Revises: 5797a5167e94
Create Date: 2026-07-09 19:47:47.679978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa8d5f63f640'
down_revision: Union[str, None] = '5797a5167e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('initiated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_records'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('recipient_kind', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_table('availability_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('end_time_local', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('generation_watermark', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user_profiles.id'], name=op.f('fk_availability_patterns_coach_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_patterns'))
    )
    op.create_table('cancellation_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('programme_id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=True),
    sa.Column('cancellation_window_hours', sa.Integer(), nullable=False),
    sa.Column('cancellation_allowed_by', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user_profiles.id'], name=op.f('fk_cancellation_policies_coach_id_user_profiles')),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_cancellation_policies_programme_id_programmes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancellation_policies'))
    )
    op.create_table('unavailability_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('end_time_local', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('on_behalf_of_coach_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user_profiles.id'], name=op.f('fk_unavailability_blocks_coach_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unavailability_blocks'))
    )
    op.create_table('unavailability_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('end_time_local', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('on_behalf_of_coach_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user_profiles.id'], name=op.f('fk_unavailability_patterns_coach_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unavailability_patterns'))
    )
    op.create_table('availability_pattern_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('on_behalf_of_coach_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['availability_patterns.id'], name=op.f('fk_availability_pattern_versions_pattern_id_availability_patterns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_pattern_versions')),
    sa.UniqueConstraint('pattern_id', 'version', name=op.f('uq_availability_pattern_versions_pattern_id_version'))
    )
    op.create_table('slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=True),
    sa.Column('pattern_version', sa.Integer(), nullable=True),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user_profiles.id'], name=op.f('fk_slots_coach_id_user_profiles')),
    sa.ForeignKeyConstraint(['pattern_id'], ['availability_patterns.id'], name=op.f('fk_slots_pattern_id_availability_patterns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots')),
    sa.UniqueConstraint('coach_id', 'start_utc', 'end_utc', name=op.f('uq_slots_coach_id_start_utc_end_utc'))
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('programme_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('acting_user_id', sa.String(), nullable=False),
    sa.Column('on_behalf_of_coach_id', sa.String(), nullable=True),
    sa.Column('booking_language_matched', sa.Boolean(), nullable=False),
    sa.Column('booking_preferred_language', sa.String(), nullable=True),
    sa.Column('original_appointment_id', sa.String(), nullable=True),
    sa.Column('cancelled_by', sa.String(), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('no_show_detection', sa.String(), nullable=True),
    sa.Column('no_show_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user_profiles.id'], name=op.f('fk_appointments_coach_id_user_profiles')),
    sa.ForeignKeyConstraint(['member_id'], ['user_profiles.id'], name=op.f('fk_appointments_member_id_user_profiles')),
    sa.ForeignKeyConstraint(['original_appointment_id'], ['appointments.id'], name=op.f('fk_appointments_original_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_appointments_programme_id_programmes')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_appointments_slot_id_slots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_appointments_idempotency_key'))
    )
    op.create_index('uq_appointments_slot_confirmed', 'appointments', ['slot_id'], unique=True, postgresql_where=sa.text("status = 'confirmed'"))
    op.create_table('reassignment_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('from_coach_id', sa.String(), nullable=False),
    sa.Column('to_coach_id', sa.String(), nullable=False),
    sa.Column('from_slot_id', sa.String(), nullable=False),
    sa.Column('to_slot_id', sa.String(), nullable=False),
    sa.Column('initiating_user_id', sa.String(), nullable=False),
    sa.Column('on_behalf_of_coach_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_reassignment_events_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['from_coach_id'], ['user_profiles.id'], name=op.f('fk_reassignment_events_from_coach_id_user_profiles')),
    sa.ForeignKeyConstraint(['from_slot_id'], ['slots.id'], name=op.f('fk_reassignment_events_from_slot_id_slots')),
    sa.ForeignKeyConstraint(['to_coach_id'], ['user_profiles.id'], name=op.f('fk_reassignment_events_to_coach_id_user_profiles')),
    sa.ForeignKeyConstraint(['to_slot_id'], ['slots.id'], name=op.f('fk_reassignment_events_to_slot_id_slots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reassignment_events'))
    )
    op.create_table('reminders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('recipient_kind', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('due_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_reminders_appointment_id_appointments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_table('reschedule_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_appointment_id', sa.String(), nullable=False),
    sa.Column('to_appointment_id', sa.String(), nullable=False),
    sa.Column('initiated_by', sa.String(), nullable=False),
    sa.Column('acting_user_id', sa.String(), nullable=False),
    sa.Column('from_slot_id', sa.String(), nullable=False),
    sa.Column('to_slot_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_appointment_id'], ['appointments.id'], name=op.f('fk_reschedule_events_from_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['from_slot_id'], ['slots.id'], name=op.f('fk_reschedule_events_from_slot_id_slots')),
    sa.ForeignKeyConstraint(['to_appointment_id'], ['appointments.id'], name=op.f('fk_reschedule_events_to_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['to_slot_id'], ['slots.id'], name=op.f('fk_reschedule_events_to_slot_id_slots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reschedule_events'))
    )
    op.create_table('reschedule_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_reschedule_tokens_appointment_id_appointments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reschedule_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_reschedule_tokens_token_hash'))
    )
    op.create_table('suggested_alternatives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cancelled_appointment_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_appointment_id'], ['appointments.id'], name=op.f('fk_suggested_alternatives_cancelled_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_suggested_alternatives_slot_id_slots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggested_alternatives')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_suggested_alternatives_token_hash'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_alternatives')
    op.drop_table('reschedule_tokens')
    op.drop_table('reschedule_events')
    op.drop_table('reminders')
    op.drop_table('reassignment_events')
    op.drop_index('uq_appointments_slot_confirmed', table_name='appointments', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_table('appointments')
    op.drop_table('slots')
    op.drop_table('availability_pattern_versions')
    op.drop_table('unavailability_patterns')
    op.drop_table('unavailability_blocks')
    op.drop_table('cancellation_policies')
    op.drop_table('availability_patterns')
    op.drop_table('outbox_events')
    op.drop_table('notifications')
    op.drop_table('call_records')
    # ### end Alembic commands ###
