"""reading queue retry visibility delay

Revision ID: aedf37dd40b7
Revises: 45ecb77282f3
Create Date: 2026-07-14 14:23:36.321934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aedf37dd40b7'
down_revision: Union[str, None] = '45ecb77282f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_queue', sa.Column('visible_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_queue', 'visible_at')
    # ### end Alembic commands ###
