"""drop member_details

 (revision history): drop the
``member_details`` table. Since moved the preferred language onto the
profile, the row was a bare member-role marker — and role membership is already
read from ``user_roles`` (the single role read path), so the marker added
nothing. A member-specific detail table returns only when a member-only field
first exists.

The downgrade recreates the table at its current shape (``user_id`` PK +
timestamps — the ``preferred_language`` column was already dropped by
``5cd17e752ff3``); it does not restore rows, which the marker never carried
beyond membership.

Revision ID: d63d5b060509
Revises: 289bf468c1eb
Create Date: 2026-07-24 11:18:04.047109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd63d5b060509'
down_revision: Union[str, None] = '289bf468c1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_details',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_member_details_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_member_details'))
    )
    # ### end Alembic commands ###
