################################################################################
# Cognito Module - User Pool, App Client, Domain
################################################################################

resource "aws_cognito_user_pool" "main" {
  name = "${var.name_prefix}-user-pool"

  # Username configuration
  username_attributes      = ["email"]
  auto_verified_attributes = ["email"]

  # Password policy
  password_policy {
    minimum_length                   = var.password_minimum_length
    require_lowercase                = true
    require_uppercase                = true
    require_numbers                  = true
    require_symbols                  = true
    temporary_password_validity_days = 7
  }

  # Account recovery
  account_recovery_setting {
    recovery_mechanism {
      name     = "verified_email"
      priority = 1
    }
  }

  # Schema attributes
  schema {
    name                     = "email"
    attribute_data_type      = "String"
    required                 = true
    mutable                  = true
    developer_only_attribute = false

    string_attribute_constraints {
      min_length = 1
      max_length = 256
    }
  }

  # MFA configuration
  mfa_configuration = var.mfa_configuration

  software_token_mfa_configuration {
    enabled = true
  }

  # Email configuration
  email_configuration {
    email_sending_account = "COGNITO_DEFAULT"
  }

  tags = merge(var.tags, {
    Name = "${var.name_prefix}-user-pool"
  })
}

# Cognito User Pool Domain (hosted UI)
resource "aws_cognito_user_pool_domain" "main" {
  domain       = "${var.name_prefix}-auth"
  user_pool_id = aws_cognito_user_pool.main.id
}

# App Client for Strata.Engine.Auth service
resource "aws_cognito_user_pool_client" "strata_engine_auth" {
  name         = "${var.name_prefix}-engine-auth-client"
  user_pool_id = aws_cognito_user_pool.main.id

  # Token validity
  access_token_validity  = var.access_token_validity_hours
  id_token_validity      = var.id_token_validity_hours
  refresh_token_validity = var.refresh_token_validity_days

  token_validity_units {
    access_token  = "hours"
    id_token      = "hours"
    refresh_token = "days"
  }

  # Auth flows
  explicit_auth_flows = [
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
    "ALLOW_USER_SRP_AUTH",
  ]

  # OAuth settings
  allowed_oauth_flows                  = ["code"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes                 = ["email", "openid", "profile"]
  callback_urls                        = var.callback_urls
  logout_urls                          = var.logout_urls
  supported_identity_providers         = ["COGNITO"]

  # Security
  prevent_user_existence_errors = "ENABLED"
  generate_secret               = false
}

# Resource Server (optional - for custom scopes)
resource "aws_cognito_resource_server" "api" {
  count = length(var.resource_server_scopes) > 0 ? 1 : 0

  identifier   = "https://api.${var.name_prefix}.com"
  name         = "${var.name_prefix}-api"
  user_pool_id = aws_cognito_user_pool.main.id

  dynamic "scope" {
    for_each = var.resource_server_scopes
    content {
      scope_name        = scope.value.name
      scope_description = scope.value.description
    }
  }
}

################################################################################
# Role Groups
#
# The application's role catalogue (strata_identity.roles.GROUP_BY_ROLE)
# expects these three groups to already exist -- AdminAddUserToGroup fails
# with ResourceNotFoundException on a group that was never created.
# Confirmed missing entirely in a real environment: develop had them
# (created by hand, undocumented, at some point before this module
# existed), uat never did, so every UAT user provisioned via
# scripts/provision_users.py got a correct database role but an empty
# /v1/auth/me roles list (that endpoint resolves roles from Cognito group
# membership, not the database directly).
################################################################################

resource "aws_cognito_user_group" "coach" {
  name         = "coach"
  user_pool_id = aws_cognito_user_pool.main.id
}

resource "aws_cognito_user_group" "member" {
  name         = "member"
  user_pool_id = aws_cognito_user_pool.main.id
}

resource "aws_cognito_user_group" "admin" {
  name         = "admin"
  user_pool_id = aws_cognito_user_pool.main.id
}

################################################################################
# Initial Users
#
# Replicates the "Create user" flow from the Cognito console:
#   - email as username
#   - email marked as verified
#   - a real, random temporary password (generated by this module, not
#     supplied) -- user must change it on first login
#
# Add emails via var.initial_user_emails -- no password is ever supplied
# or stored in git for these; Terraform generates one per user itself.
################################################################################

# One real random password per initial user. length/override_special chosen
# to satisfy Cognito's default password policy (upper/lower/number/symbol)
# without using characters Cognito's policy sometimes rejects in practice.
resource "random_password" "initial_user" {
  for_each = var.initial_user_emails

  length           = 16
  special          = true
  override_special = "!@#$%^&*()-_=+"

  # A real apply proved why these matter: this pool's password_policy
  # requires all four character classes (lower/upper/number/symbol), but
  # `special`/`upper`/`lower`/`numeric` above only put each class INTO the
  # pool of characters random_password draws from -- they don't guarantee
  # the final result actually contains one. Several of the 18 real
  # passwords generated without a min_* setting had zero digits and were
  # rejected outright ("Password must have numeric characters"). The
  # min_* arguments force at least one of each class into every result,
  # deterministically satisfying the policy instead of leaving it to
  # chance on a 16-character draw.
  min_lower   = 1
  min_upper   = 1
  min_numeric = 1
  min_special = 1
}

resource "aws_cognito_user" "initial" {
  for_each = var.initial_user_emails

  user_pool_id       = aws_cognito_user_pool.main.id
  username           = each.value
  temporary_password = random_password.initial_user[each.key].result

  attributes = {
    email          = each.value
    email_verified = "true"
  }

  # Manage creation only -- ignore password/attribute changes made after
  # first apply (console resets, user profile updates, etc.)
  lifecycle {
    ignore_changes = [
      temporary_password,
      attributes,
    ]
  }
}
