"""The field-level data-classification catalog.

Every column of every canonical table carries a data classification — the
vocabulary is 's: ``clinical`` (PHI) · ``personal`` (PII) ·
``internal``. Service-level classification binds the log-safety rules on the
write path; this catalog makes the sensitivity travel with the **data**, so
any consumer — a reading service, a human, an AI session — can look up a
field before handling it (reads are open across domains).

Explicit per column ON PURPOSE: a new column cannot inherit a table default
silently — the completeness test fails the build until the column is
classified here, in the same PR as its model and migration (the ownership-
registry forcing function, one level down). ``CLASSIFICATIONS.md`` is the
human-readable half; judgement calls are flagged there for the owner.
"""

from typing import Final, Literal

Classification = Literal["clinical", "personal", "internal"]

#: table -> column -> classification. Kept in table order; every canonical
#: column appears exactly once (enforced by tests/test_classifications.py).
FIELD_CLASSIFICATIONS: Final[dict[str, dict[str, Classification]]] = {
    "active_ingredients": {
        "id": "internal",
        "product_pk": "internal",
        "ord": "internal",
        "name": "internal",
        "strength": "internal",
    },
    "appointments": {
        "id": "personal",
        "slot_id": "personal",
        "coach_id": "personal",
        "member_id": "personal",
        "programme_id": "clinical",
        "status": "personal",
        "created_by": "personal",
        "acting_user_id": "personal",
        "on_behalf_of_coach_id": "personal",
        "booking_language_matched": "personal",
        "booking_preferred_language": "personal",
        "original_appointment_id": "personal",
        "cancelled_by": "personal",
        "cancellation_reason": "personal",
        "no_show_detection": "personal",
        "no_show_detected_at": "personal",
        "idempotency_key": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "availability_pattern_versions": {
        "id": "personal",
        "pattern_id": "personal",
        "version": "personal",
        "snapshot": "personal",
        "changed_by": "personal",
        "on_behalf_of_coach_id": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "availability_patterns": {
        "id": "personal",
        "coach_id": "personal",
        "days_of_week": "personal",
        "start_time_local": "personal",
        "end_time_local": "personal",
        "slot_duration_minutes": "personal",
        "timezone": "personal",
        "active_from": "personal",
        "active_to": "personal",
        "version": "personal",
        "status": "personal",
        "generation_watermark": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "blood_pressure_readings": {
        "id": "clinical",
        "user_id": "clinical",
        "device_id": "clinical",
        "provider_reading_id": "clinical",
        "recorded_at": "clinical",
        "received_at": "clinical",
        "systolic_mmhg": "clinical",
        "diastolic_mmhg": "clinical",
        "pulse_bpm": "clinical",
        "irregular": "clinical",
        "suspect": "clinical",
        "correlation_id": "clinical",
        "raw_ref": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "call_records": {
        "id": "personal",
        "coach_id": "personal",
        "member_id": "personal",
        "initiated_at_utc": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "cancellation_policies": {
        "id": "internal",
        "scope": "internal",
        "programme_id": "internal",
        "coach_id": "internal",
        "cancellation_window_hours": "internal",
        "cancellation_allowed_by": "internal",
        "version": "internal",
        "active": "internal",
        "created_at": "internal",
        "updated_at": "internal",
    },
    "diagnoses": {
        "id": "internal",
        "code": "internal",
        "short_title": "internal",
        "long_title": "internal",
        "order_number": "internal",
        "ingested_at": "internal",
    },
    "languages": {"code": "internal", "created_at": "internal", "updated_at": "internal"},
    # The clinical domain: a member's health profile — every
    # column clinical, including ids and timestamps (the row's existence links a
    # person to a condition/procedure/medication). Keyed on ``user_id``.
    "member_demographics": {
        "member_user_id": "clinical",
        "sex": "clinical",
        "date_of_birth": "clinical",
        "ethnicity": "clinical",
        "marital_status": "clinical",
        "height_in": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "member_diagnoses": {
        "id": "clinical",
        "member_user_id": "clinical",
        "code": "clinical",
        "starts_on": "clinical",
        "ends_on": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "member_medications": {
        "id": "clinical",
        "member_user_id": "clinical",
        "product_id": "clinical",
        "note": "clinical",
        "starts_on": "clinical",
        "ends_on": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "member_procedures": {
        "id": "clinical",
        "member_user_id": "clinical",
        "code": "clinical",
        "starts_on": "clinical",
        "ends_on": "clinical",
        "status": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "notifications": {
        "id": "personal",
        "channel": "personal",
        "recipient_kind": "personal",
        "recipient_id": "personal",
        "notification_type": "personal",
        "payload": "clinical",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "outbox_events": {
        "id": "personal",
        "event_type": "personal",
        "payload": "clinical",
        "occurred_at": "personal",
        "published_at": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "packagings": {
        "id": "internal",
        "product_pk": "internal",
        "package_ndc": "internal",
        "description": "internal",
        "marketing_start_date": "internal",
        "marketing_end_date": "internal",
        "sample": "internal",
    },
    "procedures": {
        "id": "internal",
        "code": "internal",
        "short_title": "internal",
        "long_title": "internal",
        "order_number": "internal",
        "ingested_at": "internal",
    },
    "product_identifiers": {
        "id": "internal",
        "product_pk": "internal",
        "system": "internal",
        "value": "internal",
    },
    "products": {
        "id": "internal",
        "product_id": "internal",
        "product_ndc": "internal",
        "brand_name": "internal",
        "brand_name_base": "internal",
        "generic_name": "internal",
        "labeler_name": "internal",
        "dosage_form": "internal",
        "product_type": "internal",
        "marketing_category": "internal",
        "marketing_start_date": "internal",
        "marketing_end_date": "internal",
        "listing_expiration_date": "internal",
        "dea_schedule": "internal",
        "application_number": "internal",
        "spl_id": "internal",
        "finished": "internal",
        "routes": "internal",
        "pharm_classes": "internal",
        "raw": "internal",
        "ingested_at": "internal",
    },
    "programme_assignments": {
        "id": "clinical",
        "programme_id": "clinical",
        "user_id": "clinical",
        "role_id": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "programmes": {
        "id": "internal",
        "name": "internal",
        "suggestion_window_hours": "internal",
        "reassignment_notification_enabled": "internal",
        "no_show_grace_minutes": "internal",
        "reminder_lead_hours": "internal",
        "slot_horizon_weeks": "internal",
        "reschedule_link_ttl_days": "internal",
        "created_at": "internal",
        "updated_at": "internal",
    },
    "quarantined_readings": {
        "id": "clinical",
        "correlation_id": "clinical",
        "raw_ref": "clinical",
        "device_id": "clinical",
        "reading_type": "clinical",
        "state": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "raw_readings": {
        "id": "clinical",
        "payload": "clinical",
        "correlation_id": "clinical",
        "received_at": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "reading_queue": {
        "id": "clinical",
        "raw_ref": "clinical",
        "correlation_id": "clinical",
        "state": "clinical",
        "receive_count": "clinical",
        "last_error": "clinical",
        "visible_at": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "readings_outbox_events": {
        "id": "clinical",
        "event_type": "clinical",
        "payload": "clinical",
        "occurred_at": "clinical",
        "published_at": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
    "reassignment_events": {
        "id": "personal",
        "appointment_id": "personal",
        "from_coach_id": "personal",
        "to_coach_id": "personal",
        "from_slot_id": "personal",
        "to_slot_id": "personal",
        "initiating_user_id": "personal",
        "on_behalf_of_coach_id": "personal",
        "occurred_at": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "reminders": {
        "id": "personal",
        "appointment_id": "personal",
        "recipient_kind": "personal",
        "recipient_id": "personal",
        "due_at_utc": "personal",
        "status": "personal",
        "sent_at": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "reschedule_events": {
        "id": "personal",
        "from_appointment_id": "personal",
        "to_appointment_id": "personal",
        "initiated_by": "personal",
        "acting_user_id": "personal",
        "from_slot_id": "personal",
        "to_slot_id": "personal",
        "occurred_at": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "reschedule_tokens": {
        "id": "personal",
        "appointment_id": "personal",
        "token_hash": "personal",  # nosec B105 (classification label, not a secret)
        "audience": "personal",
        "expires_at": "personal",
        "used_at": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "roles": {
        "id": "internal",
        "name": "internal",
        "created_at": "internal",
        "updated_at": "internal",
    },
    "slots": {
        "id": "personal",
        "coach_id": "personal",
        "pattern_id": "personal",
        "pattern_version": "personal",
        "start_utc": "personal",
        "end_utc": "personal",
        "duration_minutes": "personal",
        "status": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "suggested_alternatives": {
        "id": "personal",
        "cancelled_appointment_id": "personal",
        "rank": "personal",
        "kind": "personal",
        "slot_id": "personal",
        "token_hash": "personal",  # nosec B105 (classification label, not a secret)
        "status": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "unavailability_blocks": {
        "id": "personal",
        "coach_id": "personal",
        "date": "personal",
        "start_time_local": "personal",
        "end_time_local": "personal",
        "timezone": "personal",
        "created_by": "personal",
        "on_behalf_of_coach_id": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "unavailability_patterns": {
        "id": "personal",
        "coach_id": "personal",
        "days_of_week": "personal",
        "start_time_local": "personal",
        "end_time_local": "personal",
        "timezone": "personal",
        "active_from": "personal",
        "active_to": "personal",
        "status": "personal",
        "created_by": "personal",
        "on_behalf_of_coach_id": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "user_external_id_types": {
        "id": "internal",
        "name": "internal",
        "created_at": "internal",
        "updated_at": "internal",
    },
    "user_external_ids": {
        "id": "personal",
        "user_id": "personal",
        "type_id": "personal",
        "external_id": "personal",
        "registered_at": "personal",
        "ended_at": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "user_languages": {
        "id": "personal",
        "user_id": "personal",
        "language_code": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "user_profiles": {
        "id": "personal",
        "email": "personal",
        "first_name": "personal",
        "last_name": "personal",
        "display_name": "personal",
        "timezone": "personal",
        "preferred_language_code": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "user_roles": {
        "id": "personal",
        "user_id": "personal",
        "role_id": "personal",
        "created_at": "personal",
        "updated_at": "personal",
    },
    "weight_readings": {
        "id": "clinical",
        "user_id": "clinical",
        "device_id": "clinical",
        "provider_reading_id": "clinical",
        "recorded_at": "clinical",
        "received_at": "clinical",
        "weight_kg": "clinical",
        "tare_kg": "clinical",
        "weight_lbs": "clinical",
        "tare_lbs": "clinical",
        "suspect": "clinical",
        "correlation_id": "clinical",
        "raw_ref": "clinical",
        "created_at": "clinical",
        "updated_at": "clinical",
    },
}


def classification_for(table_name: str, column_name: str) -> Classification:
    """The classification of ``table.column`` (KeyError = not canonical/unclassified)."""
    return FIELD_CLASSIFICATIONS[table_name][column_name]
