"""The one declarative Base for the canonical metadata.

Single ``public`` schema (owner decision 09-07-2026): provenance lives in
the code layout (``strata_core.domains.*``) and the ownership registry, not in
Postgres namespaces. The naming convention makes autogenerated constraint names
deterministic, so migrations and the drift check never disagree over names.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
